/**
 * @file radarlistdialog.h
 * @author  Peter Mikula <mikula.ptr@gmail.com>
 * @version 1.0
 * @brief This class is about to create GUI window for managing radar units imported into program.
 *
 * @section DESCRIPTION
 *
 * Radar_handlers contains basic information about all radars known for application and used for
 * data processing. This window allows to list these into table and quick edit individual parameters.
 * Also functionality of removing/adding new radar units is present.
 *
 * Since synthetic data are used for testing, for better comfort, functionality for reading data directly
 * from setup.txt file generated by Coordinate generator was added. Note that during accessing
 * radar list and settings object, mutex lock are neccessar, since it is used accross the application.
 *
 */

#ifndef RADARLISTDIALOG_H
#define RADARLISTDIALOG_H

#include <QDialog>
#include <QMutex>
#include <QVector>
#include <QCheckBox>
#include <QLabel>
#include <QHBoxLayout>
#include <QFileDialog>
#include <QDir>
#include <QFile>
#include <QMessageBox>

#include "uwbsettings.h"
#include "radarunit.h"
#include "radar_handler.h"

namespace Ui {
class radarListDialog;
}

class radarListDialog : public QDialog
{
    Q_OBJECT

public:
    explicit radarListDialog(QVector<radar_handler * > * radar_List, QMutex * radar_List_Mutex, uwbSettings * setts, QMutex * settings_Mutex, QWidget *parent = 0);
    ~radarListDialog();

private:
    Ui::radarListDialog *ui;

    const double PI;

    void addRadarUnit(bool enabled, int id, double x_pos, double y_pos, double angle);
    int findFreeId(void);

    uwbSettings * settings;
    QMutex * settingsMutex;

    QVector<radar_handler * > * radarList;
    QMutex * radarListMutex;

    QString rememberedValue;

    enum tableColumns
    {
        ENABLE, ID, X, Y, ANGLE
    };

    double convertToRadians(double angle);
    double convertToDegrees(double angle);

private slots:
    void importFromFileSlot(void);
    void deselectAllSlot(void);
    void selectAllSlot(void);
    void clearListSlot(void);
    void cellChangedControlSlot(int row, int column);
    void cellClickedRememberSlot(int row, int column);
    void addRadarUnitSlot(void);
    void rowSelectionSlot(void);
    void deleteRadarUnitSlot(void);
    void accepted(void);

signals:
    void radarListUpdated(void);
};

#endif // RADARLISTDIALOG_H
